# Generated by Django 3.2.9 on 2021-12-14 21:51

import django.contrib.auth.validators
from django.db import migrations, models
import forza_auth.models


class Migration(migrations.Migration):

    dependencies = [
        ('forza_auth', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default=forza_auth.models.get_default_username, error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
