# Generated by Django 3.2.9 on 2021-12-03 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='xCoord',
        ),
        migrations.RemoveField(
            model_name='event',
            name='yCoord',
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('xCoord', models.IntegerField()),
                ('yCoord', models.IntegerField()),
                ('main_event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_locations', to='events.event')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='events.location'),
            preserve_default=False,
        ),
    ]
