# Generated by Django 3.2.9 on 2021-12-14 21:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('number', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='open',
            field=models.BooleanField(default=True, help_text='Whether records can still be added to an event or not.'),
        ),
        migrations.AddField(
            model_name='event',
            name='performance_class',
            field=models.IntegerField(blank=True, choices=[(1, 'D'), (2, 'C'), (3, 'B'), (4, 'A'), (5, 'S1'), (6, 'S2'), (7, 'X')], null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='season',
            field=models.IntegerField(blank=True, choices=[(1, 'Spring'), (2, 'Summer'), (3, 'Autumn'), (4, 'Winter')], null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='seasonal',
            field=models.BooleanField(default=False, help_text='Is this a seasonal event or not'),
        ),
        migrations.AlterField(
            model_name='event',
            name='active',
            field=models.BooleanField(default=True, help_text='Delete an event by marking it inactive.'),
        ),
        migrations.AddField(
            model_name='event',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.series'),
        ),
    ]
