# Generated by Django 3.2.9 on 2021-12-14 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20211214_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='series',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Series',
        ),
    ]
