# Generated by Django 3.2.9 on 2021-12-15 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20211214_2206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='kind',
        ),
        migrations.RemoveField(
            model_name='event',
            name='seasonal',
        ),
        migrations.RemoveField(
            model_name='location',
            name='main_event',
        ),
        migrations.AddField(
            model_name='location',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='location',
            name='kind',
            field=models.ForeignKey(default=717884376896569345, on_delete=django.db.models.deletion.CASCADE, to='events.eventkind'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='seasonal',
            field=models.BooleanField(default=False, help_text='Is this a seasonal event or not'),
        ),
    ]
