# Generated by Django 3.2.9 on 2021-12-10 01:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='xCoord',
            new_name='x',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='yCoord',
            new_name='y',
        ),
        migrations.AddField(
            model_name='event',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='eventkind',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='location',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
