# Generated by Django 3.2.9 on 2021-12-14 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboards', '0001_initial'),
        ('forza_cars', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Brands',
            new_name='Brand',
        ),
        migrations.RenameModel(
            old_name='Cars',
            new_name='Car',
        ),
    ]
