# Generated by Django 3.2.9 on 2021-12-15 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20211214_2206'),
        ('leaderboards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='leaderboard',
        ),
        migrations.AddField(
            model_name='record',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='leaderboards', to='events.event'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Leaderboard',
        ),
    ]
