# Generated by Django 3.2.9 on 2021-12-15 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboards', '0002_auto_20211215_0609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='name',
        ),
    ]
